### ISSUE TITLE
Would you mind sharing the org mode yasnippet template?

### ISSUE THREAD

**Issue by toinfty** [dschrempf/emacs-initialization#1]
Thanks for sharing your Emacs configurations! 

I have learnt a lot from your configurations. I am now trying to build a personal web page like you did using org-mode. I found that you use yasnippet to insert org file headers in this line (https://github.com/dschrempf/emacs-initialization/blob/master/init-org-mode.el#L494) which could be very handy. Would you mind sharing this yasnippet template (`dom-blog-post`)?

**Comment by dschrempf** [comment]
Hello,

thank you very much for your interest!  The code in the snippet is:

    # -*- mode: snippet; require-final-newline: nil -*-
    # name: dom-blog-post
    # key: bh
    # binding: direct-keybinding
    # --
    #+TITLE: ${1:Title}
    #+DATE: <`(format-time-string "%Y-%m-%d %a")`>
    #+AUTHOR: Dominik Schrempf
    #+DESCRIPTION: ${2:Description}
    #+KEYWORDS: ${3:Keywords}
    #+LANGUAGE: en

At the moment, I am also looking into using Org mode export with Jekyll
and the Bootstrap style.  This may also be interesting to you!

http://getbootstrap.com/

Cheers,
Dominik

**Comment by toinfty** [comment]
Thanks a lot! I will stay tuned. :smile:
